    INCLUDE 'MC9S08JM16.INC' 
	
KBIE	EQU	1
KBACK	EQU	2
KMOD    EQU 0
CLK		EQU 0		
RESET   EQU 1
LOCK	EQU	6	
RS		EQU	0		
ENABLE	EQU	1
TRIGER	EQU 3; triger del sensor		
LRESET	EQU 3;
CLKSA	EQU	3;
TOF		EQU	7;
CH2F	EQU	7;
CH2		EQU	7;
CONT1	EQU	2;
CONT2	EQU	1;
CONT3	EQU	4;
CONT4	EQU	5;

LLENAR  EQU 0
VACIAR	EQU 1

		ORG 	0B0H  					;Direccion de RAM  (Variables)
CONT	DS 1	
V_I 	DS 1
V_F		DS 1
T_O		DS 1	
INF		DS 2
SUP 	DS 2	
AUX		DS 1

		ORG		0C000H; 				Direccion de RAM  (Memoria para programa)

INICIO: CLRA
		STA		SOPT1
		LDHX	#4B0H
		TXS
		MOV     #0AAH,MCGTRM
		MOV     #00000110B,MCGC1
		BRCLR	LOCK,	MCGSC,	*
		MOV		#33H,	PTFDD	  ;Configuramos los pines F0,F1,F4,F5	como salidas	
		MOV		#00101000B,	PTCDD	  ;Configuracion del reloj para sensor PTC5 - PIN 44	
		BSET	LRESET,PTCD;
		LDHX 	#50000D
		JSR     TIEMPO
		MOV		#00010110B, IRQSC; CONFIGURACION IRQ
		BCLR	LRESET,PTCD;
		MOV		#0H,PTGDD;
		LDA		#0FH			 	;HABILITAR RESISTENCIAS DE PULL UP G2-G3
		STA		PTGPE				;MODIFICA REGISTRO	
		MOV		#11000011B,KBIPE	;HABILITAR INTERRUPCIONES DE PUERTOS
		MOV		#00000000B,KBIES	;SE CONFIGURA FLANCO DE BAJADA 	
		BSET	KBACK, KBISC
		BSET	KBIE,  KBISC
		MOV     #0H,KBIES
		CLI
		;------------------INICIALIZACION--------------------------
		MOV		#0H,V_I;
		MOV		#0H,V_F;
		MOV		#0H,T_O;
		MOV		#0H,AUX;
		BCLR	TRIGER,PTCD
		;------------------CONFIGURACION LCD--------------------------------------------
CON_LCD:LDHX	#50000D
		JSR		TIEMPO		
		MOV		#0FFH,	PTEDD			;Configuramos el puerto E todo como salidas
		MOV		#3H,PTDDD			;Configuramos bits 0 y 1 del puerto D como salidas
		BCLR	ENABLE,	PTDD				;Mandamos el bit 1 del registro D a 0
		MOV 	#00111000B,	PTED			;Enviamos el comando para colocar bus a 8 BITS, las 2 lineas habilitadas y matriz de 5x7 en cada cuadro
		JSR		COMANDO					;Saltamos a sub rutina para enviar el comando
		MOV		#00000110B,	PTED			;Enviamos el comando para escribir de izquierda a derecha y display estático
		JSR		COMANDO					;Saltamos a sub turtina para enviar el comando
		MOV		#00001100B,	PTED			;Enviamos el comando para encender el display, apagar el cursor y mantener el cursor estático
		JSR		COMANDO					;Saltamos a sub rutina para enviar el comando
		MOV 	#00000001B,	PTED			;Enviamos el comando para borrar el display
		JSR		COMANDO
		LDHX	#20000D
		JSR		TIEMPO
		MOV		#10000000B,	PTED			;Enviamos comando para mover el cursor a la posición 2 en la línea 1
		JSR		COMANDO
		LDHX	#0H
		JSR		CLRLCD;
;---------Configuracion Timers----------------		 
		MOV		#0H,CONT;
		MOV		#00000000B,TPM1SC; DESABILITA LA INTERUPCION, TIMER DESACTIVADO Y PRESCALER DE 1
		MOV		#00000001B,TPM2SC;	DESABILITA INTERUPCION, TIMER DESACTIVADO Y PRESCALER DE 128
		MOV		#0F4H,TPM2MODH
		MOV		#24H,TPM2MODL
		MOV		#01011000B,TPM2C0SC; CONFIGURACION CANAL
		MOV 	#0H,TPM2C0VH;
		MOV 	#1H,TPM2C0VL;
		BSET	CLKSA,TPM1SC; HABILITA CONTADOR CON REFERENCIAS EN BUS CLOCK
		BSET	CLKSA,TPM2SC;
;------------- CICLO INFINTO-------------
CICLO:	BRCLR	TOF,TPM2SC,*; PREGUNTA SI PASO UN 1S
		BCLR	TOF,TPM2SC; LIMPIA BANDERA
		BCLR	CH2,TPM2C0SC
		BSET	TRIGER,PTCD
		LDHX	#0H;
		STHX	TPM2CNT; REINICIO CONTADOR
		;------------------------------------
		;BRCLR	CH2F,TPM2C0SC,*;
		;BCLR	CH2F,TPM2C0SC		
		;MOV		#01000111B,TPM2SC;	HABILITA INTERUPCION, TIMER HABILITADO Y PRESCALER DE 1
		
		;BCLR	CH2F,TPM1SC; LIMPIA BANDERA
		;BSET	CLKSA,TPM2SC; ----------
		;LDHX	#0050H; CARGA VALOR PAR 10 us
		;STHX	TPM2MOD; ----- CARGA VALOR DE 10 us
		;BSET	TRIGER,PTCD
		;-------------------
		;MOV		#00000100B,TPM1C2SC; 01 FLANCO DE SUBIDA PARA TPM1-CH2 REGISTRO DE CONTROL STATUS
		;BRCLR	CH2F,TPM1SC,*;
		;BCLR	CH2F,TPM1C2SC;
		;LDHX	TPM1CNTH; REINICIO CONTADOR
		;MOV		#00001000B,TPM1C2SC; FLANCO DE BAJADA PARA TPM1-CH2 REGISTRO DE CONTROL STATUS
		;BRCLR	CH2F,TPM1C2SC,*
		;BCLR	CH2F,TPM1C2SC;
		;LDHX	TPM1C2VH;
		;JSR		NIVEL;
		;MOV		#00000111B,TPM2SC;	DESABILITA INTERUPCION, TIMER DESACTIVADO Y PRESCALER DE 128
		;LDHX	#0F424H; CARGA VALOR PAR 1 s
		;STHX	TPM2MOD; -----
		;BSET	CLKSA,TPM2SC; ----------
		;JSR 	CONTEO
		;LDA		AUX;
		;CBEQA	#1H,FINCI
FINCI:	JMP 	CICLO;RETORNA AL WHILE INFINITO		
;--------------------SUBRUTINA NIVEL
NIVEL:  LDX		INF+1
		LDA		INF+0
		PSHA
		PULH
		CPHX	TPM2CNTH
		BPL		SACAR
		BSET	LLENAR,PTCD
		BCLR	VACIAR,PTCD
		RTS
SACAR:	LDX		SUP+1
		LDA		SUP+0
		PSHA
		PULH
		CPHX	TPM2CNTH
		BPL		APAGAR
		BCLR	LLENAR,PTCD
		BSET	VACIAR,PTCD
		RTS
APAGAR: BCLR	LLENAR,PTCD
		BCLR	VACIAR,PTCD
		RTS
	  	RTS
;----------------------SUBRUTINA LIMITES-------------------------
LIMITES:LDA		#223D
		LDX      V_F      ; Distancia x2
		MUL
		STX		INF+0
		STA		INF+1
		
		LDA		#223D
		LDX		V_F        ; Distancia x2
		MUL
		STX		SUP+0
		STA		SUP+1
		RTS				
;------
INT_CH2:BCLR	CH2,TPM2C0SC
		BCLR	TRIGER,PTCD	;
		RTI					;

;-------------------INTERRUPCION TM2CH0---------------------------------
INT_TM2:BCLR	CH2,TPM2SC
		BCLR	TRIGER,PTCD	;
		MOV		#00000111B,TPM2SC;	DESABILITA INTERUPCION, TIMER DESACTIVADO Y PRESCALER DE 128
		;MOV		#0H,AUX		;
		RTI					; RETORNA DE INTERRUPCION
		
		
				
;-------------------INTERRUPCION KBI------------------------------------		
INT_KBI:BCLR	TRIGER,PTCD
		LDA		AUX			;SE PREGNTA POR EL AUXILIAR 
		CBEQA	#0H,FDOWN			;
FUP:	MOV		#1H,AUX				;
		MOV		#00000000B,KBIES	;SE CONFIGURA FLANCO DE BAJADA
		BSET	KBACK, KBISC		;
		JSR		CONTEO;
		;MOV		#0H,CONT; CONT=0;
		;MOV		#00010011B,PTFD;
		RTI;	
FDOWN:	LDA 	PTGD
		AND 	#0FH
		CBEQA   #0EH,F1
		CBEQA 	#0DH,F2
		CBEQA   #0BH,F3
		CBEQA   #07H,F4
F1:		LDA		CONT;
		CBEQA	#1H,F1C1;
		CBEQA	#2H,F1C2;
		CBEQA	#3H,F1C3;
F1C4:	;LDA	#41H;
		JMP     KBIEXIT
F1C3:	;LDA		#33H;
		MOV		#3H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F1C2:	;LDA		#32H;
		MOV		#2H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F1C1:	;LDA		#31H;
		MOV		#1H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT			
F2:  	LDA		CONT;
		CBEQA	#1H,F2C1;
		CBEQA	#2H,F2C2;
		CBEQA	#3H,F2C3;
F2C4:	;LDA	#42H;
		JMP    KBIEXIT
F2C3:	;LDA		#36H;
		MOV		#6H, T_O; 
		JSR		ING_NUM;
		JMP     KBIEXIT
F2C2:	;LDA		#35H;
		MOV		#5H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F2C1:	;LDA		#34H;
		MOV		#4H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT	
F3:		LDA		CONT;
		CBEQA	#1H,F3C1;
		CBEQA	#2H,F3C2;
		CBEQA	#3H,F3C3;
F3C4:	;LDA	#43H;
		JSR		BORRAR;
		JMP     KBIEXIT
F3C3:	;LDA	#39H;
		MOV		#9H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F3C2:	;LDA	#38H;
		MOV		#8H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F3C1:	;LDA	#37H;
		MOV		#7H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT			
F4:		LDA		CONT;
		CBEQA	#1H,F4C1;
		CBEQA	#2H,F4C2;
		CBEQA	#3H,F4C3;
F4C4:	;LDA	#44H;
		JSR 	INTRO;
		MOV		#1H,AUX; AUX = 1;
		LDA		KBIES;		
		MOV		#11111111B,KBIES	;SE CONFIGURA FLANCO DE SUBIDA  
		BSET	KBACK,KBISC; ELIMINA REBOTE
		;JSR 	ACT_NVL
		RTI
F4C3:	;LDA	#23H;
		JMP    KBIEXIT
F4C2:	;LDA	#30H;
		MOV		#0H,T_O;
		JSR		ING_NUM;
		JMP     KBIEXIT
F4C1:	;LDA		#2AH;
		JMP     KBIEXIT					
KBIEXIT:JSR 	ACT_LCD;
		MOV		#1H,AUX; AUX = 1;
		MOV		#11111111B,KBIES	;SE CONFIGURA FLANCO DE SUBIDA  
		BSET	KBACK, KBISC
		;MOV		#00110011B,PTFD;
		RTI
;--------RUTINA CONTADOR--------------------------------
CONTEO:	LDA		CONT;
		CBEQA	#0,CONT_1;
		CBEQA	#1,CONT_2;
		CBEQA	#2,CONT_3;
CONT_4:	MOV		#0H,CONT; 
		BSET	CONT1,PTCD;
		BSET	CONT2,PTFD;
		BSET	CONT3,PTFD;
		BCLR	CONT4,PTFD; 		
		JMP		CEXIT;
CONT_3:	INC		CONT
		BSET	CONT1,PTCD;
		BSET	CONT2,PTFD;
		BCLR	CONT3,PTFD;
		BSET	CONT4,PTFD;
		JMP		CEXIT;
CONT_2:	INC		CONT
		BSET	CONT1,PTCD;
		BCLR	CONT2,PTFD;
		BSET	CONT3,PTFD;
		BSET	CONT4,PTFD;
		JMP		CEXIT;
CONT_1:	INC		CONT
		BCLR	CONT1,PTCD;
		BSET	CONT2,PTFD;
		BSET	CONT3,PTFD;
		BSET	CONT4,PTFD;		
CEXIT:	RTS;		

;--------RUTINA COMANDO---------------------------------- 
COMANDO:BCLR	RS,		PTDD				;Mandamos el bit RS del LCD al 0 para saber que vamos a enviar un comando
		JMP		SALTOLCD					;Pasamos a hacer el pulso del enable
DATOLCD:BSET	RS,		PTDD				;Mandamos el bit RS del LCD a 1 para saber que vamos a enviar un dato
SALTOLCD:
		BSET	ENABLE,	PTDD				;Mandamos el pulso en alto al bit ENABLE del LCD
		NOP									;Con esto esperamos tiempo en alto del bit ENABLE		
		NOP
		NOP									;Con esto esperamos tiempo en alto del bit ENABLE		
		NOP
		NOP
		NOP
		BCLR	ENABLE,	PTDD				;Bajamos el bit a 0 y así aseguramos el pulso
		PSHX								;Guarda datos correspondientes lo que venia antes  
		PSHH								;para subrutina de tiempo no sobre escriba
		LDHX	#50D
		JSR		TIEMPO
		PULH								;Obtiene 
		PULX								;Datos
		RTS
;------------ OPERACION A NUMERO INGRESADO----------------------
ING_NUM:LDA		#10D     ; 
		CMP 	V_I     ;A-OPR8
		BPL 	AJ1
		RTS
		
AJ1:    LDX 	V_I
		MUL
		ADD 	T_O
		STA 	V_I
		RTS

INTRO:  LDA 	#25D
		CMP 	V_I
		BPL 	MENOR			;SALTA SI ES MENOR
		MOV		#0H,V_I
		MOV		#11001110B,PTED
		JSR 	COMANDO
		MOV 	#4EH,PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO
		MOV		#11001111B,PTED
		JSR		COMANDO
		MOV		#41H,PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO	
		RTS
MENOR: 	MOV 	V_F, V_I
		MOV		#0H,V_I
		MOV		#11001110B,PTED
		JSR 	COMANDO
		MOV 	#2DH,PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO
		MOV		#11001111B,PTED
		JSR		COMANDO
		MOV		#2DH,PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO	
		RTS
BORRAR: MOV		#0H,V_I;
		RTS
;-------------ACTUALIZA LCD-------------------
ACT_LCD:LDHX 	#10D
		LDA     V_I
		DIV
		PSHH
		ADD 	#30H
		MOV		#11001110B,PTED
		JSR 	COMANDO
		STA 	PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO
		PULA
		ADD		#30H
		MOV		#11001111B,PTED
		JSR		COMANDO
		STA 	PTED
		JSR 	DATOLCD
		LDHX	#1000D
		JSR		TIEMPO
		RTS
;-------------------------------------------------------------
CLRLCD:
LINEA1: LDA 	TABLAF1,X
		CBEQA	#0FFH,CONLIN2
		STA		PTED
		JSR		DATOLCD
		AIX 	#1H
		JMP		LINEA1
CONLIN2:MOV		#11000000B,PTED			; ENVIAMOS COMANDO PARA MVER EL CURSOR EN LA POSICION 2 DE LA LINEA 2
		JSR     COMANDO
		LDHX 	#20000D
		JSR     TIEMPO
LINEA2:	LDA 	TABLAF2,X               ; Se preguntan por datos de la tabla
		CBEQA	#0FFH,EXITLCD
		STA		PTED
		JSR		DATOLCD
		AIX 	#1H
		JMP		LINEA2;
EXITLCD:RTS


;--------INICIO RUTINA DE TIEMPO------------------------------
TIEMPO: AIX		#-1D         ; resta 1 a HX
		CPHX	#0H          ; compara HX con 0
		BNE		TIEMPO       ; Si hx es igual a 0 sigue
		RTS                  ; retorna		

		
TABLAN: FCB  '0123456789',0FFH
TABLAF1:FCB 'NIVEL ACTUAL:   ',0FFH
TABLAF2:FCB 'NIVEL FINAL :   ',0FFH
			
;------POSICION DE INICIO----------------------------------
		ORG		0FFCCH
		FDB		INT_KBI
		
		ORG     0FFFEH
		FDB		INICIO
		
		ORG		0FFDAH
		FDB		INT_TM2
		
		ORG		0FFDEH
		FDB		INT_CH2;
